language: php
dist: trusty

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - '/^[[:digit:]]+\.x'
    - '/^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/'

matrix:
  include:
    - php: 7.3
      env: 'DEPENDENCIES=highest'
    - php: 7.2
    - php: 7.1
    - php: 7.1
      env: 'DEPENDENCIES=lowest'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - '.scenarios.lock/install "${SCENARIO}" "${DEPENDENCIES}"'

script:
  - composer test

after_success:
  - 'travis_retry php vendor/bin/php-coveralls -v'
